<?php

namespace ControlF\GenemuDemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentoRepository extends EntityRepository
{
}
