<?php

namespace ControlF\GenemuDemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends EntityRepository
{
}
