<?php

namespace ControlF\GenemuDemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends EntityRepository
{
}
