<?php

namespace G4\Inventory\InventoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CondicionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionesRepository extends EntityRepository
{
}
